server:
  port: 8080

spring:
  application:
    name: customer-service
  datasource:
    url: jdbc:postgresql://localhost:5432/outdoors
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver
    jpa:
      hibernate:
        ddl-auto: update
      show-sql: true
