server:
  port: 8080

spring:
  application:
    name: customer-service
  datasource:
    url: jdbc:postgresql://localhost:5432/outdoors
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver
    jpa:
      hibernate:
        ddl-auto: update
      show-sql: true

  springdoc:
    api-docs:
      enabled: true
      path: /v3/api-docs
    swagger-ui:
      enabled: true
      path: /swagger-ui.html
      operationsSorter: method
      tagsSorter: alpha
      displayRequestDuration: true
      defaultModelsExpandDepth: 1
      defaultModelExpandDepth: 1
      tryItOutEnabled: false

  info:
    app:
      name: '@project.name@'
      description: '@project.description@'
      version: '@project.version@'
      encoding: '@project.build.sourceEncoding@'
      java:
        version: '@java.version@'

  flyway:
    enabled: true
    baseline-on-migrate: true
